In [2]:
import numpy as np
import pandas as pd

In [3]:
#import dataset
device_2022 = pd.read_csv('/srv/data/my_shared_data_folder//iet_2022/filtered_netrics_latency_202205.csv', header=None)
device_2022

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,2022-05-05 23:51:00,nm-mngd-20210518-19941862,ping_latency,rtt,icmp,Atlanta,0.0,avg,60649,att,39.296,chicago,73.176.1.0,1
1,2022-05-05 23:51:00,nm-mngd-20210518-19941862,ping_latency,rtt,icmp,Atlanta,0.0,max,60649,att,44.864,chicago,73.176.1.0,1
2,2022-05-05 23:51:00,nm-mngd-20210518-19941862,ping_latency,rtt,icmp,Atlanta,0.0,mdev,60649,att,2.044,chicago,73.176.1.0,1
3,2022-05-05 23:51:00,nm-mngd-20210518-19941862,ping_latency,rtt,icmp,Atlanta,0.0,min,60649,att,37.110,chicago,73.176.1.0,1
4,2022-05-05 23:51:00,nm-mngd-20210518-19941862,ping_latency,rtt,icmp,Chicago,0.0,avg,60649,att,14.601,chicago,73.176.1.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
685395,2022-05-03 23:21:00,nm-mngd-20210518-19941862,last_mile_rtt,rtt,icmp,Cloudflare,0.0,ping_mdev,60649,att,0.449,chicago,73.176.1.0,0
685396,2022-05-03 23:21:00,nm-mngd-20210518-19941862,last_mile_rtt,rtt,icmp,Cloudflare,0.0,ping_min,60649,att,9.879,chicago,73.176.1.0,0
685397,2022-05-03 23:21:00,nm-mngd-20210518-19941862,last_mile_rtt,rtt,icmp,Cloudflare,0.0,tr_max,60649,att,16.890,chicago,73.176.1.0,0
685398,2022-05-03 23:21:00,nm-mngd-20210518-19941862,last_mile_rtt,rtt,icmp,Cloudflare,0.0,tr_median,60649,att,16.706,chicago,73.176.1.0,0
685399,2022-05-03 23:21:00,nm-mngd-20210518-19941862,last_mile_rtt,rtt,icmp,Cloudflare,0.0,tr_min,60649,att,10.196,chicago,73.176.1.0,0

In [4]:
#created a variable named all_files containing all 12 files
all_files = ["filtered_netrics_latency_202201.csv", "filtered_netrics_latency_202207.csv",
             "filtered_netrics_latency_202202.csv", "filtered_netrics_latency_202208.csv",
            "filtered_netrics_latency_202203.csv",  "filtered_netrics_latency_202209.csv",
            "filtered_netrics_latency_202204.csv",  "filtered_netrics_latency_202210.csv",
            "filtered_netrics_latency_202205.csv",  "filtered_netrics_latency_202211.csv",
            "filtered_netrics_latency_202206.csv",  "filtered_netrics_latency_202212.csv"]

In [5]:
#ran first index value to make sure it ran correctly
all_files[0]

'filtered_netrics_latency_202201.csv'

In [6]:
#created a variable name containing path for the 12 files
path="/srv/data/my_shared_data_folder//iet_2022/"

In [7]:
#created a variable name containing the correct column names
columns = ['time','deviceid','tool','direction','protocol','target','pktloss','method','zip','isp','value','topic','annonipaddr','ipaddrchanged']

In [8]:
#read in all 12 files under dataframe "device_2022"
device_2022 = pd.read_csv(path + 'filtered_netrics_latency_202201.csv',names=columns)
device_2022

,time,deviceid,tool,direction,protocol,target,pktloss,method,zip,isp,value,topic,annonipaddr,ipaddrchanged
0,2022-01-03 18:26:07,nm-mngd-20210518-19941862,ping_latency,rtt,icmp,Atlanta,0.0,avg,60649,att,43.394,chicago,108.237.217.0,0
1,2022-01-03 18:26:07,nm-mngd-20210518-19941862,ping_latency,rtt,icmp,Atlanta,0.0,max,60649,att,44.146,chicago,108.237.217.0,0
2,2022-01-03 18:26:07,nm-mngd-20210518-19941862,ping_latency,rtt,icmp,Atlanta,0.0,mdev,60649,att,0.514,chicago,108.237.217.0,0
3,2022-01-03 18:26:07,nm-mngd-20210518-19941862,ping_latency,rtt,icmp,Atlanta,0.0,min,60649,att,42.709,chicago,108.237.217.0,0
4,2022-01-03 18:26:07,nm-mngd-20210518-19941862,ping_latency,rtt,icmp,Chicago,0.0,avg,60649,att,20.881,chicago,108.237.217.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
693711,2022-01-06 03:01:18,nm-mngd-20210518-19941862,last_mile_rtt,rtt,icmp,Cloudflare,0.0,ping_mdev,60649,att,0.452,chicago,108.237.217.0,0
693712,2022-01-06 03:01:18,nm-mngd-20210518-19941862,last_mile_rtt,rtt,icmp,Cloudflare,0.0,ping_min,60649,att,17.487,chicago,108.237.217.0,0
693713,2022-01-06 03:01:18,nm-mngd-20210518-19941862,last_mile_rtt,rtt,icmp,Cloudflare,0.0,tr_max,60649,att,22.076,chicago,108.237.217.0,0
693714,2022-01-06 03:01:18,nm-mngd-20210518-19941862,last_mile_rtt,rtt,icmp,Cloudflare,0.0,tr_median,60649,att,20.860,chicago,108.237.217.0,0
693715,2022-01-06 03:01:18,nm-mngd-20210518-19941862,last_mile_rtt,rtt,icmp,Cloudflare,0.0,tr_min,60649,att,19.332,chicago,108.237.217.0,0

In [9]:
#for loop in order to read in each file
for file in all_files:
    df = pd.read_csv(path + file, names=columns)
    device_2022 = pd.concat([device_2022,df])

In [10]:
#sorted vales
device_2022 = device_2022.sort_values(by=['time'])
device_2022.tail()

,time,deviceid,tool,direction,protocol,target,pktloss,method,zip,isp,value,topic,annonipaddr,ipaddrchanged
157473,2022-11-19 05:55:59,nm-mngd-20210518-19941862,ping_latency,rtt,icmp,amazon,0.0,min,60649,att,10.646,chicago,73.176.1.0,0
157472,2022-11-19 05:55:59,nm-mngd-20210518-19941862,ping_latency,rtt,icmp,amazon,0.0,mdev,60649,att,1.962,chicago,73.176.1.0,0
157471,2022-11-19 05:55:59,nm-mngd-20210518-19941862,ping_latency,rtt,icmp,amazon,0.0,max,60649,att,16.883,chicago,73.176.1.0,0
157480,2022-11-19 05:55:59,nm-mngd-20210518-19941862,ping_latency,rtt,icmp,google,0.0,mdev,60649,att,1.432,chicago,73.176.1.0,0
157476,2022-11-19 05:55:59,nm-mngd-20210518-19941862,ping_latency,rtt,icmp,facebook,0.0,mdev,60649,att,0.943,chicago,73.176.1.0,0

In [11]:
#Located all the average latency values
device_22avg = device_2022.loc[device_2022['method'] == 'avg']
device_22avg

,time,deviceid,tool,direction,protocol,target,pktloss,method,zip,isp,value,topic,annonipaddr,ipaddrchanged
555961,2021-12-31 18:00:05,nm-mngd-20210518-19941862,ping_latency,rtt,icmp,google,9.09091,avg,60649,att,108.639,chicago,108.237.217.0,0
555961,2021-12-31 18:00:05,nm-mngd-20210518-19941862,ping_latency,rtt,icmp,google,9.09091,avg,60649,att,108.639,chicago,108.237.217.0,0
538492,2021-12-31 18:01:33,nm-mngd-20210518-19941862,ping_latency,rtt,icmp,Chicago,0.00000,avg,60649,att,22.307,chicago,108.237.217.0,0
538540,2021-12-31 18:01:33,nm-mngd-20210518-19941862,ping_latency,rtt,icmp,tribune,0.00000,avg,60649,att,34.187,chicago,108.237.217.0,0
538536,2021-12-31 18:01:33,nm-mngd-20210518-19941862,ping_latency,rtt,icmp,suntimes,0.00000,avg,60649,att,34.252,chicago,108.237.217.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
157470,2022-11-19 05:55:59,nm-mngd-20210518-19941862,ping_latency,rtt,icmp,amazon,0.00000,avg,60649,att,12.567,chicago,73.176.1.0,0
157486,2022-11-19 05:55:59,nm-mngd-20210518-19941862,ping_latency,rtt,icmp,tribune,0.00000,avg,60649,att,11.396,chicago,73.176.1.0,0
157482,2022-11-19 05:55:59,nm-mngd-20210518-19941862,ping_latency,rtt,icmp,suntimes,0.00000,avg,60649,att,12.125,chicago,73.176.1.0,0
157478,2022-11-19 05:55:59,nm-mngd-20210518-19941862,ping_latency,rtt,icmp,google,0.00000,avg,60649,att,12.170,chicago,73.176.1.0,0
157474,2022-11-19 05:55:59,nm-mngd-20210518-19941862,ping_latency,rtt,icmp,facebook,0.00000,avg,60649,att,11.912,chicago,73.176.1.0,0

In [12]:
#Located only 3 servers: Atlanta, Seattle, and Chicago
device_2022 = device_22avg.loc[device_22avg['target'].isin(['Atlanta', 'Seattle', 'Chicago'])]
device_2022.head()

,time,deviceid,tool,direction,protocol,target,pktloss,method,zip,isp,value,topic,annonipaddr,ipaddrchanged
538492,2021-12-31 18:01:33,nm-mngd-20210518-19941862,ping_latency,rtt,icmp,Chicago,0.0,avg,60649,att,22.307,chicago,108.237.217.0,0
538488,2021-12-31 18:01:33,nm-mngd-20210518-19941862,ping_latency,rtt,icmp,Atlanta,0.0,avg,60649,att,95.486,chicago,108.237.217.0,0
538492,2021-12-31 18:01:33,nm-mngd-20210518-19941862,ping_latency,rtt,icmp,Chicago,0.0,avg,60649,att,22.307,chicago,108.237.217.0,0
538508,2021-12-31 18:01:33,nm-mngd-20210518-19941862,ping_latency,rtt,icmp,Seattle,0.0,avg,60649,att,84.930,chicago,108.237.217.0,0
538488,2021-12-31 18:01:33,nm-mngd-20210518-19941862,ping_latency,rtt,icmp,Atlanta,0.0,avg,60649,att,95.486,chicago,108.237.217.0,0

In [13]:
#Function to split hour from the time column
def split_hour(time):
    row = time
    return row[11:13]

device_2022.loc[:,"hour"] = device_2022.loc[:,"time"].apply(split_hour)

/tmp/ipykernel_1908418/1063256170.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  device_2022.loc[:,"hour"] = device_2022.loc[:,"time"].apply(split_hour)

In [14]:
#Function to split date from time column
def split_date(time):
    row = time
    return row[:10]

device_2022.loc[:,"date"] = device_2022.loc[:,"time"].apply(split_date)

/tmp/ipykernel_1908418/3755401069.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  device_2022.loc[:,"date"] = device_2022.loc[:,"time"].apply(split_date)

In [15]:
#Function to split month from time column
def split_month(x):
    row = x
    return row[5:7]

device_2022.loc[:,"month"] = device_2022.loc[:,"time"].apply(split_month)

/tmp/ipykernel_1908418/39249147.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  device_2022.loc[:,"month"] = device_2022.loc[:,"time"].apply(split_month)

In [16]:
#Called dataframe
device_2022

,time,deviceid,tool,direction,protocol,target,pktloss,method,zip,isp,value,topic,annonipaddr,ipaddrchanged,hour,date,month
538492,2021-12-31 18:01:33,nm-mngd-20210518-19941862,ping_latency,rtt,icmp,Chicago,0.0,avg,60649,att,22.307,chicago,108.237.217.0,0,18,2021-12-31,12
538488,2021-12-31 18:01:33,nm-mngd-20210518-19941862,ping_latency,rtt,icmp,Atlanta,0.0,avg,60649,att,95.486,chicago,108.237.217.0,0,18,2021-12-31,12
538492,2021-12-31 18:01:33,nm-mngd-20210518-19941862,ping_latency,rtt,icmp,Chicago,0.0,avg,60649,att,22.307,chicago,108.237.217.0,0,18,2021-12-31,12
538508,2021-12-31 18:01:33,nm-mngd-20210518-19941862,ping_latency,rtt,icmp,Seattle,0.0,avg,60649,att,84.930,chicago,108.237.217.0,0,18,2021-12-31,12
538488,2021-12-31 18:01:33,nm-mngd-20210518-19941862,ping_latency,rtt,icmp,Atlanta,0.0,avg,60649,att,95.486,chicago,108.237.217.0,0,18,2021-12-31,12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
164977,2022-11-19 05:50:59,nm-mngd-20210518-19941862,ping_latency,rtt,icmp,Chicago,0.0,avg,60649,att,43.870,chicago,73.176.1.0,0,05,2022-11-19,11
164993,2022-11-19 05:50:59,nm-mngd-20210518-19941862,ping_latency,rtt,icmp,Seattle,0.0,avg,60649,att,64.916,chicago,73.176.1.0,0,05,2022-11-19,11
157454,2022-11-19 05:55:59,nm-mngd-20210518-19941862,ping_latency,rtt,icmp,Seattle,0.0,avg,60649,att,62.641,chicago,73.176.1.0,0,05,2022-11-19,11
157438,2022-11-19 05:55:59,nm-mngd-20210518-19941862,ping_latency,rtt,icmp,Chicago,0.0,avg,60649,att,13.484,chicago,73.176.1.0,0,05,2022-11-19,11
157434,2022-11-19 05:55:59,nm-mngd-20210518-19941862,ping_latency,rtt,icmp,Atlanta,0.0,avg,60649,att,38.296,chicago,73.176.1.0,0,05,2022-11-19,11

In [17]:
#Chagned the hour column from a string to integer
device_2022.hour = device_2022['hour'].astype('int')
print(device_2022.dtypes)

time              object
deviceid          object
tool              object
direction         object
protocol          object
target            object
pktloss          float64
method            object
zip               object
isp               object
value            float64
topic             object
annonipaddr       object
ipaddrchanged     object
hour               int64
date              object
month             object
dtype: object

/tmp/ipykernel_1908418/2629516228.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  device_2022.hour = device_2022['hour'].astype('int')

In [18]:
#Created an anomaly detection function using the mean and one standard deviation
def anomaly_detec(x):
        stdev_threshold = x.std() + x.mean()
        print(stdev_threshold)
        anomaly_total = x >= stdev_threshold
        return anomaly_total
    
    
anomaly_detec(device_2022['value'])

#Created a new column "anomalytotal" which applies the anomaly detection function to the value column
device_2022["anomalytotal"]=anomaly_detec(device_2022['value'])

#device_5["anomalytotal"] = device_5["value"].apply(anomaly_detec)

/tmp/ipykernel_1908418/1192335977.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  device_2022["anomalytotal"]=anomaly_detec(device_2022['value'])

82.60564418355776
82.60564418355776

In [19]:
#Called the head of the value column with the applied anom. det. function
anomaly_detec(device_2022['value']).head()

82.60564418355776

538492    False
538488     True
538492    False
538508     True
538488     True
Name: value, dtype: bool

In [21]:
device_2022["anomalytotal"] = anomaly_detec(device_2022['value'])

pd.set_option('display.max_rows', None)

82.60564418355776

/tmp/ipykernel_1908418/567358533.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  device_2022["anomalytotal"] = anomaly_detec(device_2022['value'])

In [22]:
#Called tail of anomalytotal column
device_2022["anomalytotal"].tail()

164977    False
164993    False
157454    False
157438    False
157434    False
Name: anomalytotal, dtype: bool

In [23]:
#Grouped month, date, and target from the device 2022 dataframe. 
anomaly_22 = device_2022.groupby(['month','date','target'])[['anomalytotal']].sum()
anomaly_22.head()

                          anomalytotal
month date       target
01    2022-01-01 Atlanta            60
                 Chicago            46
                 Seattle            84
      2022-01-02 Atlanta           106
                 Chicago            96

In [36]:
#Grouped by just month and target, then pulled the monthly median anomaly totals
anomalymonth_22 = anomaly_22.groupby(['month','target'])[['anomalytotal']].median()
anomalymonth_22

               anomalytotal
month target
01    Atlanta          50.0
      Chicago          34.0
      Seattle          82.0
02    Atlanta          30.0
      Chicago          20.0
      Seattle          49.5
03    Atlanta          26.0
      Chicago          14.0
      Seattle          42.0
04    Atlanta           0.0
      Chicago           0.0
      Seattle           0.0
05    Atlanta           0.0
      Chicago           0.0
      Seattle           0.0
06    Atlanta           0.0
      Chicago           0.0
      Seattle           0.0
07    Atlanta           0.0
      Chicago           0.0
      Seattle           0.0
08    Atlanta           0.0
      Chicago           0.0
      Seattle           0.0
09    Atlanta           0.0
      Chicago           0.0
      Seattle           0.0
10    Atlanta           0.0
      Chicago           0.0
      Seattle           0.0
11    Atlanta           0.0
      Chicago           0.0
      Seattle           0.0
12    Atlanta           8.0
      Chicago           2.0
      Seattle          28.0

In [37]:
#imported packages for plotting
import matplotlib as mpl
import matplotlib.pyplot as plt

import seaborn as sns
import seaborn.objects as so
import plotly.express as px
import plotly.graph_objs as go

In [38]:
from dash import Dash, dcc, html, Input, Output
import plotly.express as px

app = Dash(__name__)


app.layout = html.Div([
    html.H4('Median Anomalies per Month'),
    dcc.Dropdown(
        id="dropdown",
        options=["Atlanta", "Chicago", "Seattle"],
        value="Atlanta",
        clearable=False,
    ),
    dcc.Graph(id="graph"),
])


@app.callback(
    Output("graph", "figure"), 
    Input("dropdown", "value"))
def update_bar_chart(server):
    mask = anomalymonth_2022["target"] == server
    fig = px.bar(anomalymonth_2022[mask], x="month", y="anomalytotal", 
                 color="smoker", barmode="group")
    return fig.show()

In [41]:
fig = go.Figure()

# Adding points bar plot
fig.add_trace(
    go.Bar(
        y=list(anomalymonth_22['anomalytotal']),
        x=list(anomalymonth_22['month']),
        name='Points',
        orientation='h'
    )
)

# Adding rebounds bar plot
fig.add_trace(
    go.Bar(
        y=list(df_trb['Player']),
        x=list(df_trb['TRB']),
        name='Rebounds',
        visible=False,
        orientation='h'
    )
)

# Adding assists bar plot
fig.add_trace(
    go.Bar(
        y=list(df_ast['Player']),
        x=list(df_ast['AST']),
        name='Assists',
        visible=False,
        orientation='h'
    )
)

# Minor layout adjustments
fig.update_layout(title='<b>Top 10 Leaders</b>', 
                  title_x=0.5,
                  margin=dict(t=50),
                  yaxis=dict(autorange="reversed", ticksuffix="  ")
                 )

fig.show()

KeyError: 'month'